### ISSUE TITLE
[FEATURE] Moving HP Bar

### ISSUE THREAD

**Issue by Greysion** [arbron/fvtt-hp-bar#2]
Hello!

I was hoping you might spare a moment to consider some additional features to your module.

I love all the changes you've made so far, it's been a great help to our table and I super appreciate all of your efforts.

I was wondering if you might consider another addition to your mod:

The ability to relocate the position of the health bar, if at all possible. Ideally, I would really love to display the health bar above the token's square, similar to where Roll20 displays its resource bars.

Thank you for any and all considerations. :)

**Comment by arbron** [comment]
You probably want to check out the [Bar Brawl](https://foundryvtt.com/packages/barbrawl) module which includes the ability to position bars outside the token. And it is compatible with this module :).
