### ISSUE TITLE
Advanced options are not being "saved"

### ISSUE THREAD

**Issue by ckdragons** [arbron/fvtt-hp-bar#23]
It appears that options under Advanced configuration are not being visually saved. For example, I check the Ignore Upper Limit checkbox, select either Save as default or Update Token. Open the Token properties (token itself or prototype) and the checkbox is no longer selected. It appears that the configuration is still working as expected, even when creating new tokens from the actor.

**Comment by arbron** [comment]
"Ignore Upper Limit" isn't a setting offered by this module, and it does nothing to touch token properties.

**Comment by ckdragons** [comment]
Apologies, wrong module. Meant to report to Bar Brawl.
