### ISSUE TITLE
Combatibility with Foundry v11?

### ISSUE THREAD

**Issue by ckdragons** [arbron/fvtt-hp-bar#25]
This module hasn't been updated in a year. May we expect an update to support Foundry v11?

**Comment by skepickle** [comment]
@ckdragons, I'm currently using it with the D35E system and FoundryVTT v11 without any issues. If others confirm that it's still working fine with other systems, I could put in a pull request with that change in the metadata file that might help arbron expedite this for you?

**Comment by ckdragons** [comment]
Any update to supporting v11 or v12?
