### ISSUE TITLE
[BUG] The module settings don't work

### ISSUE THREAD

**Issue by amcvfx** [arbron/fvtt-hp-bar#6]
**Describe the bug**
The module settings for the module don't seem to work. There is an error when trying to open the settings and it doesn't seem to display correctly in the module setting menu.

**Screenshots**
![image](https://user-images.githubusercontent.com/35099081/116789189-8dc8b980-aaa5-11eb-8add-3bae18390a6a.png)
![image](https://user-images.githubusercontent.com/35099081/116789202-97eab800-aaa5-11eb-9cba-5e1efe05831c.png)

**Environment:**
 - Foundry Core Version: 0.7.9
 - Module Version 2.0.0
 - Host: Forge
 - OS & Browser: Chrome

**Comment by arbron** [comment]
This is was caused by a build issue that was only up for a few minutes. Downloading the new version should resolve this, otherwise delete the module and reinstall.
